### ISSUE TITLE
`count` influences `if`?

### ISSUE THREAD

**Issue by shamrin** [witheve/lueve#8]
The following Eve program

```
ui
  [@app available filter]
  text = if available = true then "show unavailable"
         else "show available"
  total = count(given [#product available])
  maintain
    [#button text]

go
  [#session-connect]
  freeze
    [@app available: false, filter: ""]
    [#product @apple available: true]
    [#product @bread available: false]
```

produces two buttons:

``` html
<div class="program">
  <button>show available</button>
  <button>show unavailable</button>
</div>
```

While I would expect only one button:

``` html
<div class="program">
  <button>show available</button>
</div>
```

(I couldn't make the test case smaller. Everything is important to trigger the bug: `if`, `count`, even unused `filter` attribute.)

**Comment by ibdknox** [comment]
@joshuafcole this looks like an ordering issue :( The mutate is getting ordered directly after the choose, despite the fact that the choose could still be affected by the `available` attribute

**Comment by joshuafcole** [comment]
There's a deeper issue here that should get resolved at some point, but this should make it hard to impossible to trigger until we have a little more time to revisit the ordering logic for contributed terms. Please let us know if you have any further problems here

**Comment by shamrin** [comment]
Thank you! Your change fixed my Eve program.
